export enum RelationLabel {
  NO_EFFECT_AGAINST = 'NO_EFFECT_AGAINST',
  NOT_VERY_EFFECTIVE_AGAINST = 'NOT_VERY_EFFECTIVE_AGAINST',
  NORMAL_AGAINST = 'NORMAL_AGAINST',
  SUPER_EFFECTIVE_AGAINST = 'SUPER_EFFECTIVE_AGAINST'
}

export enum NodeLabel {
  TYPE = 'Type'
}
